import { TaskMap } from './types';

export const INITIAL_TASK_MAPS: TaskMap[] = [
    {
        id: 'map-trin9',
        name: 'Master Milestone Roadmap (Russian + AI Eng + MERN)',
        description: 'Comprehensive grand roadmap uniting Russian Language Fluency, AI Engineering Pipelines, and Full-Stack MERN Deployment into a single finish line.',
        color: 'purple',
        isPrimary: true,
        updatedAt: 'Just now',
        nodes: [
            // --- Track 1: Russian Language Fluency ---
            {
                id: 'node-ru-1',
                taskId: 'task_russian_mastery_r7u2k',
                subTaskId: 'sub_ru_1',
                x: 120,
                y: 100,
                customTitle: '🇷🇺 1. Cyrillic & Phonetic Basics',
            },
            {
                id: 'node-ru-2',
                taskId: 'task_russian_mastery_r7u2k',
                subTaskId: 'sub_ru_2',
                x: 440,
                y: 100,
                customTitle: '🇷🇺 2. Core 500 Vocabulary & Cases',
            },
            {
                id: 'node-ru-3',
                taskId: 'task_russian_mastery_r7u2k',
                subTaskId: 'sub_ru_5',
                x: 760,
                y: 100,
                customTitle: '🇷🇺 3. Conversational Shadowing & Fluency',
            },

            // --- Track 2: MERN Full-Stack Web Development ---
            {
                id: 'node-mern-1',
                taskId: 'task_mern_project_m3k9p',
                subTaskId: 'sub_mern_1',
                x: 120,
                y: 280,
                customTitle: '💻 1. Express API & JWT Authentication',
            },
            {
                id: 'node-mern-2',
                taskId: 'task_mern_project_m3k9p',
                subTaskId: 'sub_mern_3',
                x: 440,
                y: 280,
                customTitle: '💻 2. React 18 UI & State Management',
            },
            {
                id: 'node-mern-3',
                taskId: 'task_mern_project_m3k9p',
                subTaskId: 'sub_mern_5',
                x: 760,
                y: 280,
                customTitle: '💻 3. Docker Container & Cloud Deploy',
            },

            // --- Track 3: AI Engineering & Gemini Systems ---
            {
                id: 'node-ai-1',
                taskId: 'task_ai_engineer_a8x4m',
                subTaskId: 'sub_ai_1',
                x: 120,
                y: 460,
                customTitle: '🤖 1. Gemini SDK & Tool Calling Loops',
            },
            {
                id: 'node-ai-2',
                taskId: 'task_ai_engineer_a8x4m',
                subTaskId: 'sub_ai_3',
                x: 440,
                y: 460,
                customTitle: '🤖 2. Hybrid RAG Vector Pipeline',
            },
            {
                id: 'node-ai-3',
                taskId: 'task_ai_engineer_a8x4m',
                subTaskId: 'sub_ai_5',
                x: 760,
                y: 460,
                customTitle: '🤖 3. Autonomous Multi-Agent Orchestration',
            },

            // --- Grand Convergence Finish Node ---
            {
                id: 'node-master-finish',
                taskId: 'task_ai_engineer_a8x4m',
                x: 1100,
                y: 280,
                customTitle: '🏆 Grand Finish: Production AI Agent App & Multilingual Mastery',
            },
        ],
        connections: [
            // Russian Track Connections
            {
                id: 'c-ru-1',
                fromNodeId: 'node-ru-1',
                toNodeId: 'node-ru-2',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'c-ru-2',
                fromNodeId: 'node-ru-2',
                toNodeId: 'node-ru-3',
                relationship: 'Depends On',
                isCritical: true,
            },

            // MERN Track Connections
            {
                id: 'c-mern-1',
                fromNodeId: 'node-mern-1',
                toNodeId: 'node-mern-2',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'c-mern-2',
                fromNodeId: 'node-mern-2',
                toNodeId: 'node-mern-3',
                relationship: 'Depends On',
                isCritical: true,
            },

            // AI Track Connections
            {
                id: 'c-ai-1',
                fromNodeId: 'node-ai-1',
                toNodeId: 'node-ai-2',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'c-ai-2',
                fromNodeId: 'node-ai-2',
                toNodeId: 'node-ai-3',
                relationship: 'Depends On',
                isCritical: true,
            },

            // Cross-Track Synergy Connections
            {
                id: 'c-cross-1',
                fromNodeId: 'node-mern-2',
                toNodeId: 'node-ai-2',
                relationship: 'Supports',
            },
            {
                id: 'c-cross-2',
                fromNodeId: 'node-ai-3',
                toNodeId: 'node-mern-3',
                relationship: 'Supports',
            },

            // Convergence to Grand Finish
            {
                id: 'c-fin-1',
                fromNodeId: 'node-ru-3',
                toNodeId: 'node-master-finish',
                relationship: 'Leads To',
                isCritical: true,
            },
            {
                id: 'c-fin-2',
                fromNodeId: 'node-mern-3',
                toNodeId: 'node-master-finish',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'c-fin-3',
                fromNodeId: 'node-ai-3',
                toNodeId: 'node-master-finish',
                relationship: 'Enables',
                isCritical: true,
            },
        ],
    },
    {
        id: 'map-r7u2k',
        name: 'Russian Fluency Roadmap',
        description: 'Structured step-by-step path to master Cyrillic, core 1,000 vocabulary words, noun cases, and conversational dialogue.',
        color: 'purple',
        isPrimary: false,
        updatedAt: 'Just now',
        nodes: [
            {
                id: 'ru-node-1',
                taskId: 'task_russian_mastery_r7u2k',
                subTaskId: 'sub_ru_1',
                x: 200,
                y: 120,
                customTitle: '1. Cyrillic Alphabet & Phonetics',
            },
            {
                id: 'ru-node-2',
                taskId: 'task_russian_mastery_r7u2k',
                subTaskId: 'sub_ru_2',
                x: 520,
                y: 120,
                customTitle: '2. Top 500 Core Words (Anki SRS)',
            },
            {
                id: 'ru-node-3',
                taskId: 'task_russian_mastery_r7u2k',
                subTaskId: 'sub_ru_3',
                x: 840,
                y: 120,
                customTitle: '3. 6 Noun Cases & Conjugations',
            },
            {
                id: 'ru-node-4',
                taskId: 'task_russian_mastery_r7u2k',
                subTaskId: 'sub_ru_4',
                x: 360,
                y: 340,
                customTitle: '4. Daily Podcast Comprehension',
            },
            {
                id: 'ru-node-5',
                taskId: 'task_russian_mastery_r7u2k',
                subTaskId: 'sub_ru_5',
                x: 680,
                y: 340,
                customTitle: '5. Conversational Speech & Fluency (Finish)',
            },
        ],
        connections: [
            {
                id: 'ru-conn-1',
                fromNodeId: 'ru-node-1',
                toNodeId: 'ru-node-2',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'ru-conn-2',
                fromNodeId: 'ru-node-2',
                toNodeId: 'ru-node-3',
                relationship: 'Supports',
            },
            {
                id: 'ru-conn-3',
                fromNodeId: 'ru-node-2',
                toNodeId: 'ru-node-4',
                relationship: 'Depends On',
                isCritical: true,
            },
            {
                id: 'ru-conn-4',
                fromNodeId: 'ru-node-3',
                toNodeId: 'ru-node-5',
                relationship: 'Depends On',
                isCritical: true,
            },
            {
                id: 'ru-conn-5',
                fromNodeId: 'ru-node-4',
                toNodeId: 'ru-node-5',
                relationship: 'Leads To',
            },
        ],
    },
    {
        id: 'map-a8x4m',
        name: 'AI Engineering Mastery Path',
        description: 'Full roadmap from Gemini API foundations to Autonomous Agents, RAG vector search, and production agent benchmarks.',
        color: 'rose',
        isPrimary: false,
        updatedAt: '1h ago',
        nodes: [
            {
                id: 'ai-node-1',
                taskId: 'task_ai_engineer_a8x4m',
                subTaskId: 'sub_ai_1',
                x: 200,
                y: 120,
                customTitle: '1. Gemini API & Structured Outputs',
            },
            {
                id: 'ai-node-2',
                taskId: 'task_ai_engineer_a8x4m',
                subTaskId: 'sub_ai_2',
                x: 520,
                y: 120,
                customTitle: '2. Tool Calling & Autonomous Loops',
            },
            {
                id: 'ai-node-3',
                taskId: 'task_ai_engineer_a8x4m',
                subTaskId: 'sub_ai_3',
                x: 840,
                y: 120,
                customTitle: '3. Hybrid RAG Vector Pipeline',
            },
            {
                id: 'ai-node-4',
                taskId: 'task_ai_engineer_a8x4m',
                subTaskId: 'sub_ai_4',
                x: 360,
                y: 340,
                customTitle: '4. Context & Cost Optimization',
            },
            {
                id: 'ai-node-5',
                taskId: 'task_ai_engineer_a8x4m',
                subTaskId: 'sub_ai_5',
                x: 680,
                y: 340,
                customTitle: '5. Production Multi-Agent System (Finish)',
            },
        ],
        connections: [
            {
                id: 'ai-conn-1',
                fromNodeId: 'ai-node-1',
                toNodeId: 'ai-node-2',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'ai-conn-2',
                fromNodeId: 'ai-node-2',
                toNodeId: 'ai-node-3',
                relationship: 'Supports',
            },
            {
                id: 'ai-conn-3',
                fromNodeId: 'ai-node-2',
                toNodeId: 'ai-node-4',
                relationship: 'Depends On',
            },
            {
                id: 'ai-conn-4',
                fromNodeId: 'ai-node-3',
                toNodeId: 'ai-node-5',
                relationship: 'Depends On',
                isCritical: true,
            },
            {
                id: 'ai-conn-5',
                fromNodeId: 'ai-node-4',
                toNodeId: 'ai-node-5',
                relationship: 'Leads To',
            },
        ],
    },
    {
        id: 'map-m3k9p',
        name: 'MERN Full-Stack Delivery Roadmap',
        description: 'End-to-end plan to architect, develop, test, and ship a production-grade MERN web app to Cloud Run.',
        color: 'emerald',
        isPrimary: false,
        updatedAt: '3h ago',
        nodes: [
            {
                id: 'mern-node-1',
                taskId: 'task_mern_project_m3k9p',
                subTaskId: 'sub_mern_1',
                x: 200,
                y: 120,
                customTitle: '1. Express REST API & JWT Auth',
            },
            {
                id: 'mern-node-2',
                taskId: 'task_mern_project_m3k9p',
                subTaskId: 'sub_mern_2',
                x: 520,
                y: 120,
                customTitle: '2. Database Schema & Indexing',
            },
            {
                id: 'mern-node-3',
                taskId: 'task_mern_project_m3k9p',
                subTaskId: 'sub_mern_3',
                x: 840,
                y: 120,
                customTitle: '3. React 18 UI & State Flow',
            },
            {
                id: 'mern-node-4',
                taskId: 'task_mern_project_m3k9p',
                subTaskId: 'sub_mern_4',
                x: 360,
                y: 340,
                customTitle: '4. Optimistic CRUD & Error Boundaries',
            },
            {
                id: 'mern-node-5',
                taskId: 'task_mern_project_m3k9p',
                subTaskId: 'sub_mern_5',
                x: 680,
                y: 340,
                customTitle: '5. Docker Container & Cloud Run Live (Finish)',
            },
        ],
        connections: [
            {
                id: 'mern-conn-1',
                fromNodeId: 'mern-node-1',
                toNodeId: 'mern-node-2',
                relationship: 'Supports',
            },
            {
                id: 'mern-conn-2',
                fromNodeId: 'mern-node-2',
                toNodeId: 'mern-node-3',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'mern-conn-3',
                fromNodeId: 'mern-node-3',
                toNodeId: 'mern-node-4',
                relationship: 'Depends On',
            },
            {
                id: 'mern-conn-4',
                fromNodeId: 'mern-node-4',
                toNodeId: 'mern-node-5',
                relationship: 'Depends On',
                isCritical: true,
            },
            {
                id: 'mern-conn-5',
                fromNodeId: 'mern-node-3',
                toNodeId: 'mern-node-5',
                relationship: 'Leads To',
            },
        ],
    },
];
