import { TaskMap } from './types';

export const INITIAL_TASK_MAPS: TaskMap[] = [
    {
        id: 'map-trin9',
        name: 'Master Milestone Roadmap (Russian + AI Eng + MERN)',
        description: 'Comprehensive grand roadmap uniting Russian Language Fluency, AI Engineering Pipelines, and Full-Stack MERN Deployment into a single finish line.',
        color: 'purple',
        isPrimary: true,
        updatedAt: 'Just now',
        nodes: [
            // --- Track 1: Russian Language Fluency ---
            {
                id: 'node-ru-1',
                taskId: 'task_russian_mastery_r7u2k',
                x: 120,
                y: 100,
                customTitle: '🇷🇺 1. Cyrillic & Phonetic Basics',
                customStatus: 'completed',
                customProgress: 100,
            },
            {
                id: 'node-ru-2',
                taskId: 'task_russian_mastery_r7u2k',
                x: 440,
                y: 100,
                customTitle: '🇷🇺 2. Core 500 Vocabulary & Cases',
                customStatus: 'in_progress',
                customProgress: 60,
            },
            {
                id: 'node-ru-3',
                taskId: 'task_russian_mastery_r7u2k',
                x: 760,
                y: 100,
                customTitle: '🇷🇺 3. Conversational Shadowing & Fluency',
                customStatus: 'in_progress',
                customProgress: 35,
            },

            // --- Track 2: MERN Full-Stack Web Development ---
            {
                id: 'node-mern-1',
                taskId: 'task_mern_project_m3k9p',
                x: 120,
                y: 280,
                customTitle: '💻 1. Express API & JWT Authentication',
                customStatus: 'completed',
                customProgress: 100,
            },
            {
                id: 'node-mern-2',
                taskId: 'task_mern_project_m3k9p',
                x: 440,
                y: 280,
                customTitle: '💻 2. React 18 UI & State Management',
                customStatus: 'in_progress',
                customProgress: 70,
            },
            {
                id: 'node-mern-3',
                taskId: 'task_mern_project_m3k9p',
                x: 760,
                y: 280,
                customTitle: '💻 3. Docker Container & Cloud Deploy',
                customStatus: 'in_progress',
                customProgress: 40,
            },

            // --- Track 3: AI Engineering & Gemini Systems ---
            {
                id: 'node-ai-1',
                taskId: 'task_ai_engineer_a8x4m',
                x: 120,
                y: 460,
                customTitle: '🤖 1. Gemini SDK & Tool Calling Loops',
                customStatus: 'completed',
                customProgress: 100,
            },
            {
                id: 'node-ai-2',
                taskId: 'task_ai_engineer_a8x4m',
                x: 440,
                y: 460,
                customTitle: '🤖 2. Hybrid RAG Vector Pipeline',
                customStatus: 'in_progress',
                customProgress: 55,
            },
            {
                id: 'node-ai-3',
                taskId: 'task_ai_engineer_a8x4m',
                x: 760,
                y: 460,
                customTitle: '🤖 3. Autonomous Multi-Agent Orchestration',
                customStatus: 'todo',
                customProgress: 20,
            },

            // --- Grand Convergence Finish Node ---
            {
                id: 'node-master-finish',
                taskId: 'task_ai_engineer_a8x4m',
                x: 1100,
                y: 280,
                customTitle: '🏆 Grand Finish: Production AI Agent App & Multilingual Mastery',
                customStatus: 'in_progress',
                customProgress: 45,
            },
        ],
        connections: [
            // Russian Track Connections
            {
                id: 'c-ru-1',
                fromNodeId: 'node-ru-1',
                toNodeId: 'node-ru-2',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'c-ru-2',
                fromNodeId: 'node-ru-2',
                toNodeId: 'node-ru-3',
                relationship: 'Depends On',
                isCritical: true,
            },

            // MERN Track Connections
            {
                id: 'c-mern-1',
                fromNodeId: 'node-mern-1',
                toNodeId: 'node-mern-2',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'c-mern-2',
                fromNodeId: 'node-mern-2',
                toNodeId: 'node-mern-3',
                relationship: 'Depends On',
                isCritical: true,
            },

            // AI Track Connections
            {
                id: 'c-ai-1',
                fromNodeId: 'node-ai-1',
                toNodeId: 'node-ai-2',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'c-ai-2',
                fromNodeId: 'node-ai-2',
                toNodeId: 'node-ai-3',
                relationship: 'Depends On',
                isCritical: true,
            },

            // Cross-Track Synergy Connections
            {
                id: 'c-cross-1',
                fromNodeId: 'node-mern-2',
                toNodeId: 'node-ai-2',
                relationship: 'Supports',
            },
            {
                id: 'c-cross-2',
                fromNodeId: 'node-ai-3',
                toNodeId: 'node-mern-3',
                relationship: 'Supports',
            },

            // Convergence to Grand Finish
            {
                id: 'c-fin-1',
                fromNodeId: 'node-ru-3',
                toNodeId: 'node-master-finish',
                relationship: 'Leads To',
                isCritical: true,
            },
            {
                id: 'c-fin-2',
                fromNodeId: 'node-mern-3',
                toNodeId: 'node-master-finish',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'c-fin-3',
                fromNodeId: 'node-ai-3',
                toNodeId: 'node-master-finish',
                relationship: 'Enables',
                isCritical: true,
            },
        ],
    },
    {
        id: 'map-r7u2k',
        name: 'Russian Fluency Roadmap',
        description: 'Structured step-by-step path to master Cyrillic, core 1,000 vocabulary words, noun cases, and conversational dialogue.',
        color: 'purple',
        isPrimary: false,
        updatedAt: 'Just now',
        nodes: [
            {
                id: 'ru-node-1',
                taskId: 'task_russian_mastery_r7u2k',
                x: 200,
                y: 120,
                customTitle: '1. Cyrillic Alphabet & Phonetics',
                customStatus: 'completed',
                customProgress: 100,
            },
            {
                id: 'ru-node-2',
                taskId: 'task_russian_mastery_r7u2k',
                x: 520,
                y: 120,
                customTitle: '2. Top 500 Core Words (Anki SRS)',
                customStatus: 'in_progress',
                customProgress: 65,
            },
            {
                id: 'ru-node-3',
                taskId: 'task_russian_mastery_r7u2k',
                x: 840,
                y: 120,
                customTitle: '3. 6 Noun Cases & Conjugations',
                customStatus: 'in_progress',
                customProgress: 40,
            },
            {
                id: 'ru-node-4',
                taskId: 'task_russian_mastery_r7u2k',
                x: 360,
                y: 340,
                customTitle: '4. Daily Podcast Comprehension',
                customStatus: 'todo',
                customProgress: 10,
            },
            {
                id: 'ru-node-5',
                taskId: 'task_russian_mastery_r7u2k',
                x: 680,
                y: 340,
                customTitle: '5. Conversational Speech & Fluency (Finish)',
                customStatus: 'todo',
                customProgress: 0,
            },
        ],
        connections: [
            {
                id: 'ru-conn-1',
                fromNodeId: 'ru-node-1',
                toNodeId: 'ru-node-2',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'ru-conn-2',
                fromNodeId: 'ru-node-2',
                toNodeId: 'ru-node-3',
                relationship: 'Supports',
            },
            {
                id: 'ru-conn-3',
                fromNodeId: 'ru-node-2',
                toNodeId: 'ru-node-4',
                relationship: 'Depends On',
                isCritical: true,
            },
            {
                id: 'ru-conn-4',
                fromNodeId: 'ru-node-3',
                toNodeId: 'ru-node-5',
                relationship: 'Depends On',
                isCritical: true,
            },
            {
                id: 'ru-conn-5',
                fromNodeId: 'ru-node-4',
                toNodeId: 'ru-node-5',
                relationship: 'Leads To',
            },
        ],
    },
    {
        id: 'map-a8x4m',
        name: 'AI Engineering Mastery Path',
        description: 'Full roadmap from Gemini API foundations to Autonomous Agents, RAG vector search, and production agent benchmarks.',
        color: 'rose',
        isPrimary: false,
        updatedAt: '1h ago',
        nodes: [
            {
                id: 'ai-node-1',
                taskId: 'task_ai_engineer_a8x4m',
                x: 200,
                y: 120,
                customTitle: '1. Gemini API & Structured Outputs',
                customStatus: 'completed',
                customProgress: 100,
            },
            {
                id: 'ai-node-2',
                taskId: 'task_ai_engineer_a8x4m',
                x: 520,
                y: 120,
                customTitle: '2. Tool Calling & Autonomous Loops',
                customStatus: 'in_progress',
                customProgress: 70,
            },
            {
                id: 'ai-node-3',
                taskId: 'task_ai_engineer_a8x4m',
                x: 840,
                y: 120,
                customTitle: '3. Hybrid RAG Vector Pipeline',
                customStatus: 'in_progress',
                customProgress: 35,
            },
            {
                id: 'ai-node-4',
                taskId: 'task_ai_engineer_a8x4m',
                x: 360,
                y: 340,
                customTitle: '4. Context & Cost Optimization',
                customStatus: 'todo',
                customProgress: 0,
            },
            {
                id: 'ai-node-5',
                taskId: 'task_ai_engineer_a8x4m',
                x: 680,
                y: 340,
                customTitle: '5. Production Multi-Agent System (Finish)',
                customStatus: 'todo',
                customProgress: 0,
            },
        ],
        connections: [
            {
                id: 'ai-conn-1',
                fromNodeId: 'ai-node-1',
                toNodeId: 'ai-node-2',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'ai-conn-2',
                fromNodeId: 'ai-node-2',
                toNodeId: 'ai-node-3',
                relationship: 'Supports',
            },
            {
                id: 'ai-conn-3',
                fromNodeId: 'ai-node-2',
                toNodeId: 'ai-node-4',
                relationship: 'Depends On',
            },
            {
                id: 'ai-conn-4',
                fromNodeId: 'ai-node-3',
                toNodeId: 'ai-node-5',
                relationship: 'Depends On',
                isCritical: true,
            },
            {
                id: 'ai-conn-5',
                fromNodeId: 'ai-node-4',
                toNodeId: 'ai-node-5',
                relationship: 'Leads To',
            },
        ],
    },
    {
        id: 'map-m3k9p',
        name: 'MERN Full-Stack Delivery Roadmap',
        description: 'End-to-end plan to architect, develop, test, and ship a production-grade MERN web app to Cloud Run.',
        color: 'emerald',
        isPrimary: false,
        updatedAt: '3h ago',
        nodes: [
            {
                id: 'mern-node-1',
                taskId: 'task_mern_project_m3k9p',
                x: 200,
                y: 120,
                customTitle: '1. Express REST API & JWT Auth',
                customStatus: 'completed',
                customProgress: 100,
            },
            {
                id: 'mern-node-2',
                taskId: 'task_mern_project_m3k9p',
                x: 520,
                y: 120,
                customTitle: '2. Database Schema & Indexing',
                customStatus: 'completed',
                customProgress: 100,
            },
            {
                id: 'mern-node-3',
                taskId: 'task_mern_project_m3k9p',
                x: 840,
                y: 120,
                customTitle: '3. React 18 UI & State Flow',
                customStatus: 'in_progress',
                customProgress: 60,
            },
            {
                id: 'mern-node-4',
                taskId: 'task_mern_project_m3k9p',
                x: 360,
                y: 340,
                customTitle: '4. Optimistic CRUD & Error Boundaries',
                customStatus: 'in_progress',
                customProgress: 30,
            },
            {
                id: 'mern-node-5',
                taskId: 'task_mern_project_m3k9p',
                x: 680,
                y: 340,
                customTitle: '5. Docker Container & Cloud Run Live (Finish)',
                customStatus: 'todo',
                customProgress: 0,
            },
        ],
        connections: [
            {
                id: 'mern-conn-1',
                fromNodeId: 'mern-node-1',
                toNodeId: 'mern-node-2',
                relationship: 'Supports',
            },
            {
                id: 'mern-conn-2',
                fromNodeId: 'mern-node-2',
                toNodeId: 'mern-node-3',
                relationship: 'Enables',
                isCritical: true,
            },
            {
                id: 'mern-conn-3',
                fromNodeId: 'mern-node-3',
                toNodeId: 'mern-node-4',
                relationship: 'Depends On',
            },
            {
                id: 'mern-conn-4',
                fromNodeId: 'mern-node-4',
                toNodeId: 'mern-node-5',
                relationship: 'Depends On',
                isCritical: true,
            },
            {
                id: 'mern-conn-5',
                fromNodeId: 'mern-node-3',
                toNodeId: 'mern-node-5',
                relationship: 'Leads To',
            },
        ],
    },
];
