import { TaskMap } from './types';

export const INITIAL_TASK_MAPS: TaskMap[] = [
  {
    id: 'map-1',
    name: 'Q3 Growth Roadmap',
    description: 'Plan and execute key growth initiatives for Q3 with clear milestones.',
    color: 'purple',
    isPrimary: true,
    updatedAt: '2h ago',
    nodes: [
      {
        id: 'node-1',
        taskId: 'task-1',
        x: 480,
        y: 80,
        customTitle: 'Draft Q3 Personal Growth Blueprint',
        customStatus: 'in_progress',
        customProgress: 60,
      },
      {
        id: 'node-2',
        taskId: 'task-2',
        x: 200,
        y: 190,
        customTitle: 'Research & References',
        customStatus: 'completed',
        customProgress: 100,
      },
      {
        id: 'node-3',
        taskId: 'task-3',
        x: 480,
        y: 280,
        customTitle: 'Create Milestone Timeline',
        customStatus: 'in_progress',
        customProgress: 40,
      },
      {
        id: 'node-4',
        taskId: 'task-4',
        x: 780,
        y: 280,
        customTitle: 'Break Down Daily Habits',
        customStatus: 'todo',
        customProgress: 0,
      },
      {
        id: 'node-5',
        taskId: 'task-5',
        x: 200,
        y: 480,
        customTitle: 'Design System & Components',
        customStatus: 'todo',
        customProgress: 0,
      },
      {
        id: 'node-6',
        taskId: 'task-6',
        x: 480,
        y: 480,
        customTitle: 'Build Portfolio Website',
        customStatus: 'in_progress',
        customProgress: 30,
      },
      {
        id: 'node-7',
        taskId: 'task-7',
        x: 780,
        y: 480,
        customTitle: 'Launch Portfolio',
        customStatus: 'completed',
        customProgress: 100,
      },
    ],
    connections: [
      {
        id: 'conn-1',
        fromNodeId: 'node-2',
        toNodeId: 'node-3',
        relationship: 'Supports',
      },
      {
        id: 'conn-2',
        fromNodeId: 'node-1',
        toNodeId: 'node-3',
        relationship: 'Depends On',
        isCritical: true,
      },
      {
        id: 'conn-3',
        fromNodeId: 'node-3',
        toNodeId: 'node-4',
        relationship: 'Blocks',
      },
      {
        id: 'conn-4',
        fromNodeId: 'node-1',
        toNodeId: 'node-4',
        relationship: 'Related To',
      },
      {
        id: 'conn-5',
        fromNodeId: 'node-3',
        toNodeId: 'node-6',
        relationship: 'Depends On',
        isCritical: true,
      },
      {
        id: 'conn-6',
        fromNodeId: 'node-6',
        toNodeId: 'node-5',
        relationship: 'Related To',
      },
      {
        id: 'conn-7',
        fromNodeId: 'node-6',
        toNodeId: 'node-7',
        relationship: 'Enables',
      },
      {
        id: 'conn-8',
        fromNodeId: 'node-4',
        toNodeId: 'node-7',
        relationship: 'Leads To',
      },
      {
        id: 'conn-9',
        fromNodeId: 'node-5',
        toNodeId: 'node-7',
        relationship: 'Depends On',
        isCritical: true,
      },
    ],
  },
  {
    id: 'map-2',
    name: 'Portfolio Launch Plan',
    description: 'Everything needed to launch my portfolio website successfully.',
    color: 'emerald',
    updatedAt: '1d ago',
    nodes: [
      { id: 'p-node-1', taskId: 'task-5', x: 200, y: 150, customTitle: 'Design System', customStatus: 'completed', customProgress: 100 },
      { id: 'p-node-2', taskId: 'task-6', x: 500, y: 150, customTitle: 'Develop Frontend', customStatus: 'in_progress', customProgress: 75 },
      { id: 'p-node-3', taskId: 'task-7', x: 800, y: 150, customTitle: 'Deploy & Domain', customStatus: 'todo', customProgress: 0 },
    ],
    connections: [
      { id: 'p-conn-1', fromNodeId: 'p-node-1', toNodeId: 'p-node-2', relationship: 'Enables' },
      { id: 'p-conn-2', fromNodeId: 'p-node-2', toNodeId: 'p-node-3', relationship: 'Depends On', isCritical: true },
    ],
  },
  {
    id: 'map-3',
    name: 'Daily Habits System',
    description: 'Build and maintain daily habits that drive long term growth.',
    color: 'amber',
    updatedAt: '2d ago',
    nodes: [
      { id: 'h-node-1', taskId: 'task-4', x: 300, y: 180, customTitle: 'Morning Inspection Routine', customStatus: 'completed', customProgress: 100 },
      { id: 'h-node-2', taskId: 'task-8', x: 600, y: 180, customTitle: 'Evening Review', customStatus: 'in_progress', customProgress: 50 },
    ],
    connections: [
      { id: 'h-conn-1', fromNodeId: 'h-node-1', toNodeId: 'h-node-2', relationship: 'Leads To' },
    ],
  },
  {
    id: 'map-4',
    name: 'AI Learning Path 2024',
    description: 'Structured path to master AI engineering step by step.',
    color: 'rose',
    updatedAt: '4d ago',
    nodes: [
      { id: 'ai-node-1', taskId: 'task-9', x: 350, y: 200, customTitle: 'Gemini API Foundations', customStatus: 'in_progress', customProgress: 80 },
      { id: 'ai-node-2', taskId: 'task-10', x: 650, y: 200, customTitle: 'Agentic Workflows', customStatus: 'todo', customProgress: 0 },
    ],
    connections: [
      { id: 'ai-conn-1', fromNodeId: 'ai-node-1', toNodeId: 'ai-node-2', relationship: 'Depends On' },
    ],
  },
];
